# Global config
global:
  scrape_interval:     15s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

scrape_configs:

- job_name: consul
  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.
  consul_sd_configs:
  - server: '127.0.0.1:8500'

- job_name: nomad_statsd
  metrics_path: /metrics
  static_configs:
    - targets:
      - statsd-exporter.service.consul:9102
