---

# Docker
- name: Add docker yum repo
  template: >
    src=docker.repo
    dest=/etc/yum.repos.d/docker.repo

- name: Ensure docker is installed
  yum: name=docker-engine state=installed

- name: Ensure Docker service is started and enabled on boot
  service: name=docker state=started enabled=yes

# Nomad

- name: Create Nomad group
  group: name={{ nomad_group }} system=yes state=present

- name: Create Nomad user
  user: >
    name={{ nomad_user }}
    shell=/bin/false
    createhome=no
    group={{ nomad_group }}
    groups=docker
    system=yes
    state=present

- name: Download Nomad
  get_url: >
    url={{ nomad_url }}
    dest={{ nomad_download_dir }}/nomad.zip

- name: Ensure unzip is installed
  yum: name=unzip state=installed

- name: Unzip Nomad to installation directory
  command: unzip {{ nomad_download_dir }}/nomad.zip -d {{ nomad_install_dir }}
  args:
    creates: "{{ nomad_install_dir }}/nomad"

- name: Create Nomad configuration directory
  file: >
    path={{ nomad_config_dir }}
    owner={{ nomad_user }}
    group={{ nomad_group }}
    mode=0755
    state=directory

- name: Create Nomad data directory
  file: >
    path={{ nomad_data_dir }}
    owner={{ nomad_user }}
    group={{ nomad_group }}
    mode=0755
    state=directory

- name: Create Nomad upstart configuration
  template: >
    src=nomad.service.j2
    dest=/etc/systemd/system/nomad.service
    owner={{ nomad_user }}
    group={{ nomad_group }}
    mode=0644
  notify: restart nomad

- name: Create Nomad configuration file
  template: >
    src=base.hcl.j2
    dest={{ nomad_config_dir }}/base.hcl
    owner={{ nomad_user }}
    group={{ nomad_group }}
    mode=0644
  notify: restart nomad

- name: Create Nomad server configuration file
  template: >
    src=server.hcl.j2
    dest={{ nomad_config_dir }}/server.hcl
    owner={{ nomad_user }}
    group={{ nomad_group }}
    mode=0644
  notify: restart nomad
  when: nomad_server

- name: Create Nomad client configuration file
  template: >
    src=client.hcl.j2
    dest={{ nomad_config_dir }}/client.hcl
    owner={{ nomad_user }}
    group={{ nomad_group }}
    mode=0644
  notify: restart nomad
  when: nomad_client

- name: Ensure Nomad service is started and enabled on boot
  service: name={{ nomad_service_name }} state=started enabled=yes
